import Head from "next/head"

export default function AccountSetting()
{
    return (
        <>
        <Head>
        <title>MVR-帳號頁面</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta httpEquiv="Content-Language" content="en" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
            <h1 className="text-white m-4">更改帳號頁面</h1>
        </main>
        </>
    )
}
