import Head from "next/head"

export default function FriendList()
{
    return (
        <>
        <Head>
        <title>MVR-好友清單</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
            <h1 className="text-white m-4">好友清單頁面</h1>
        </main>
        </>
    )
}
