import React, { useState, FormEvent } from 'react';
import Head from 'next/head';
import Button from 'react-bootstrap/Button';
import Form from 'react-bootstrap/Form';
import Link from 'next/link';
import { BiShow } from 'react-icons/bi';
import axios, { AxiosError } from 'axios';
import Cookies from 'js-cookie';
import styles from './loginPage.module.css';
import TopNavbar from '../components/topnavbar';

function Password() {
    const [passwordShown, setPasswordShown] = useState(false);

    const togglePassword = () => {
        setPasswordShown(!passwordShown);
    };

    return (
        <>
            <Form.Group className={`mb-3 ${styles.inputbox}`} controlId="formBasicPassword">
                <div className="d-flex align-items-center mb-1">
                    <Form.Label className="flex-grow-1">密碼</Form.Label>
                    {/*<Button variant="light" onClick={togglePassword}>
                        <BiShow />
    </Button>*/}
                </div>
                <Form.Control
                    required
                    type={passwordShown ? 'text' : 'password'}
                    name="password"
                />
            </Form.Group>
        </>
    );
}

export default function Login() {
    const handleLogin = async (event: FormEvent<HTMLFormElement>) => {
        event.preventDefault();
        const form = event.currentTarget;
        const formData = new FormData(form);

        const data = {
            email: formData.get('account'),
            password: formData.get('password'),
        };

        try {

            await axios.post('https://b084-163-13-201-95.ngrok-free.app/api/login/', data, {
                headers: {
                    'Content-Type': 'application/json'
                }
            });
            window.alert('登入成功!!');

            Cookies.set('loggedIn', 'true', { expires: 7 });
            Cookies.set('userEmail', formData.get('account') as string, { expires: 7 });

            window.location.replace('/userPage/userSetting');
        } catch (error: any) {
            console.error(error.response?.data);
            window.alert('登入失敗!!');
        }
    };

    return (
        <>
            <Head>
                <title>MVR-登入</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            
            <main className={styles.container}>
                <div className="d-flex justify-content-center mt-4">
                    <Form onSubmit={handleLogin} className={styles.formBox}>
                        <h2 className={styles.formBoxh2}>Login</h2>
                        

                        <Form.Group className={styles.inputbox} controlId="formBasicEmail">
                            <Form.Label>Email</Form.Label>
                            <Form.Control
                                required
                                type="email"
                                name="account"
                                className="my-input"
                            />

                        </Form.Group>

                        <Password />
                        
                        <div>
                            <Button variant="primary" type="submit" className={styles.btn}>
                                Login
                            </Button>
                        </div>

                        <div className={styles.loginregister}>
                            <p>Don't have an account?
                                <Link href="/userPage/register">
                                    <span className={styles.registerLink}>Register</span>
                                </Link>
                            </p>
                        </div>
                        

                       
                    </Form>
                </div>
            </main>
        </>
    );
}
