import Head from "next/head";
import { useState, useEffect } from "react";
import axios from "axios";
import Cookies from 'js-cookie';


export default function PasswordSetting() {
    const [oldPassword, setOldPassword] = useState("");
    const [newPassword, setNewPassword] = useState("");
    const [confirmPassword, setConfirmPassword] = useState("");
    const [message, setMessage] = useState("");
    const [userId, setUserId] = useState("");
    const [verificationCode, setVerificationCode] = useState("");


    useEffect(() => {

        const userEmail = Cookies.get('userEmail') || "";
        setUserId(userEmail);
    }, []);

    const handleChangePassword = async () => {
        if (!userId) {
            setMessage("User not authenticated.");
            return;
        }

        if (newPassword !== confirmPassword) {
            setMessage("New password and confirmation do not match.");
            return;
        }

        try {
            const response = await axios.post("https://f648-163-13-201-95.ngrok-free.app/api/change_password/", {
                email: userId,
                old_password: oldPassword,
                new_password: newPassword,
            });
            window.alert(response.data.message);
            window.location.href = "/userPage/userSetting";

        } catch (error) {
            window.alert("Password change failed.")
        }
    };

    return (
        <>
            <Head>
                <title>MVR - Password Change</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <meta httpEquiv="Content-Language" content="en" />
            </Head>

            <main className="container">
                <div className="blur formBox">
                    <h2 className="title">Change Password</h2>

                    <div className="inputBox">
                        <input
                            type="password"
                            required
                            value={oldPassword}
                            onChange={(e) => setOldPassword(e.target.value)}
                        />
                        <label>Old Password</label>
                    </div>
                    
                    <div className="inputBox">
                        <input
                            type="password"
                            required
                            value={newPassword}
                            onChange={(e) => setNewPassword(e.target.value)}
                        />
                        <label>New Password</label>
                    </div>

                    <div className="inputBox">
                        <input
                            type="password"
                            required
                            value={confirmPassword}
                            onChange={(e) => setConfirmPassword(e.target.value)}
                        />
                        <label>Confirm New Password</label>
                    </div>
                    <button className="submitBtn" onClick={handleChangePassword}>
                        Change Password
                    </button>
                    {message && <p className="centerParagraph">{message}</p>}
                </div>
            </main>

            <style jsx>{`
                           
                .container {
                    height: 100%;
                    width: 100%;
                    position: relative;
                    display: flex;
                    justify-content: center;
                    align-items: center;
                    height: 100vh;
                    background-color: #e6e6e6;
                }

                .blur {
                    padding: 20px 60px;
                    border-radius: 20px;
                    width: 600px;
                    height: 500px;
                    color: black;
                    font-size: 24px;

                    font-weight: bold;
                    background: transparent;
                    border: 2px solid rgba(255, 255, 255, .5);
                    backdrop-filter: blur(20px);
                    box-shadow: 0 0 30px rgba(0, 0, 0, .5);

                    background-color: rgba(255, 255, 255, 0.9);
                    border-radius: 10px;
                    
                  
                    
                    padding: 40px;
                }

                .title {
                    text-align: center;
                    color: #162938;
                    font-weight: bold;
                    margin-bottom: 20px;
                }
                .submitBtn {
                    font-size: 0.8em;
                    width: 100%;
                    padding: 8px;
                    border: none;
                    border-radius: 5px;
                    background-color: #4d86b3;
                    color: #fff;
                    cursor: pointer;
                    font-weight: bold;
                    transition: background-color 0.3s ease;
                    margin-top: 20px;
                }

                .submitBtn:hover {
                    background-color: #3a6c97;
                }

                .centerParagraph {
                    text-align: center;
                    margin-top: 20px;
                    color: red;
                }

                .inputBox {
                    position: relative;
                    width: 100%;
                    margin: 30px 0;
                    height: 50px; 
                }

                .inputBox input {
                    font-size: 0.5em;   
                    width: 100%;
                    height: 45px;
                    background-color: transparent;
                    border: none;
                    border-bottom: 2px solid #162938;
                    padding: 5px 0;
                    font-size: 1em;
                    margin-top: 10px;  
                    font-size: 0.9em;  
                    color: #162938;
                    transition: border-color 0.3s ease;
                }
                 .inputBox input:focus {
                    border-color:#162938;
                    outline: none;
                }

                .inputBox label {
                    position: absolute;
                    bottom: 5px;
                    left: 0px;
                    font-size: 0.5em;
                    color: #162938;
                    font-weight: 500;
                    pointer-events: none;
                     transition: 0.3s, transform 0.3s;
                }

                .inputBox input:focus + label,
                .inputBox input:not(:placeholder-shown) + label {
                    transform: translateY(-25px); 
                    font-size: 0.75em;
                    color: #162938;
                }
                .formBox {
                    padding: 20px 40px;
                    border-radius: 20px;
                    width: 400px;
                    color: black;
                    background: transparent;
                    display: flex;
                    flex-direction: column;
                    align-items: center;
                    font-size: 1.5em;
                }
            `}</style>
        </>
    );
}
