import styles from './UserSetting.module.css'; 
import ListGroup from 'react-bootstrap/ListGroup';
import Link from 'next/link';
import { useRouter } from 'next/router';
import Cookies from 'js-cookie';
import Head from 'next/head';


function Menu({ handleLogout }: { handleLogout: () => void }) {
    return (
        <div className={styles.windowPane}>
        <ListGroup className={`${styles.menu} gap-2 m-3 bg-white`}>
            <Link href='passwordSetting' passHref>
                <ListGroup.Item action className={styles.menuItem}>更改密碼</ListGroup.Item>
            </Link>
            {/*
            <Link href='friendList' passHref>
                <ListGroup.Item action className={styles.menuItem}>好友清單</ListGroup.Item>
            </Link>*/
            <Link href='AccountLookup' passHref>
                <ListGroup.Item action className={styles.menuItem}>帳號資訊</ListGroup.Item>
            </Link>
    }
                <ListGroup.Item action onClick={handleLogout} className={styles.menuItem}>
                    登出
                </ListGroup.Item>

        </ListGroup>
        </div>
    );
}

export default function UserSetting() {
    const router = useRouter();

    const handleLogout = () => {
        if (window.confirm("確定要登出嗎？")) {  
        
            Cookies.remove('loggedIn');
            Cookies.remove('userEmail');
            router.push('/');
            
        }
    };

    return (
        <>
            <Head>
                <title>MVR-使用者設定</title>
                <meta name='description' content='Generated by create next app' />
                <meta name='viewport' content='width=device-width, initial-scale=1' />
                <link rel='icon' href='/favicon.ico' />
                <meta httpEquiv="Content-Language" content="en" />

            </Head>
            <main className={styles.container}>
                <Menu handleLogout={handleLogout} />
            </main>
        </>
    );
}
