import React from 'react';
import ListGroup from 'react-bootstrap/ListGroup';
import Head from 'next/head';
import Link from 'next/link';
import Cookies from 'js-cookie';
import { useRouter } from 'next/router';
import TopNavbar from '../components/topnavbar';

function Menu({ handleLogout }: { handleLogout: () => void }) {
    return (
        <ListGroup className='gap-2 m-3 bg-white'>
            <Link href='accountSetting' passHref>
                <ListGroup.Item action>更改帳號</ListGroup.Item>
            </Link>
            <Link href='passwordSetting' passHref>
                <ListGroup.Item action>更改密碼</ListGroup.Item>
            </Link>
            <Link href='friendList' passHref>
                <ListGroup.Item action>好友清單</ListGroup.Item>
            </Link>
            <Link href='accountinfo' passHref>
                <ListGroup.Item action>帳號資訊</ListGroup.Item>
            </Link>
            <ListGroup.Item action onClick={handleLogout}>
                登出
            </ListGroup.Item>
        </ListGroup>
    );
}

export default function UserSetting() {
    const router = useRouter();

    const handleLogout = () => {
        // 清除 cookies 中的使用者資料
        Cookies.remove('userEmail');
        // 跳回首頁
        router.push('/');
        // 或使用以下方式導航回首頁：
        // window.location.replace('/');
    };

    return (
        <>
            <Head>
                <title>MVR-使用者設定</title>
                <meta name='description' content='Generated by create next app' />
                <meta name='viewport' content='width=device-width, initial-scale=1' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <main>
                <Menu handleLogout={handleLogout} />
            </main>
        </>
    );
}
