import Head from 'next/head'
import Carousel from 'react-bootstrap/Carousel'
import Image from 'next/legacy/image';
import ListGroup from 'react-bootstrap/ListGroup';
import 'bootstrap/dist/css/bootstrap.min.css';
import styles from './index.module.css';
import Link from 'next/link';
import React, { useState } from 'react';

export default function Home() {


  return (
    <>
      <Head>
        <title>MVR-首頁</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <video
          src="/features_img/video.mp4"
          autoPlay
          loop
          muted
          playsInline
          className={styles.video}
        ></video>

        <div className="d-flex flex-column align-items-center justify-content-center h-100">
          <div className={styles.content}>
            <h1>MVR</h1>
            <h2>Music in nearby, Virtual Reality</h2>
            <Link href="/explore">
              <button className={styles.exploreLink}>Explore</button>
            </Link>
            
          </div>

          

        </div>

      </main>

    </>
  );
}
