import Head from 'next/head'
import Image from 'next/legacy/image';
import Stack from 'react-bootstrap/Stack';
import Slider from 'react-slick';
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

type MemberContent = {
    name: string;
    filename: string;
    work_title: string;
    work_content: string;
}

function Member({ data }: { data: MemberContent }) {
    return (
        <>
            <div className='w-25' style={{ marginLeft: '5rem' }}>
                <Image src={`/avatar/${data.filename}.webp`} alt={data.filename} width="600" height="600" className='rounded' />
            </div>
            <div className='d-flex align-items-center justify-content-center text-dark w-75'>
                <div>
                    <h2 className='fw-bolder' style={{ fontSize: '4em', color: '#4d86b3' }}>{data.name}</h2>
                    <h4 style={{ fontSize: '1.75em' }}>{data.work_title}</h4>
                    <div className='lh-base work-content-container' style={{ fontSize: '1.5em' }}>工作內容：{data.work_content}</div>
                </div>
            </div>
        </>
    );
}




export default function IntroduceTeam() {
    const settings = {
        dots: true,
        infinite: true,
        speed: 500,
        slidesToShow: 1,
        slidesToScroll: 1,
        dotsClass: "slick-dots slick-thumb",
    };

    const teamData: MemberContent[] = [
        { filename: '30448', name: '孫耀庭', work_title: '規劃流程與管理', work_content: '負責制定開發目標、短期長期目標與明確的日程規劃，後續進行追蹤與微調' },
        { filename: '30414', name: '劉宣珉', work_title: '挑選物件模型、背景與製作', work_content: '負責尋找可使用的物件資源，進行修改與調整，製作成需要的樣貌' },
        { filename: '30141', name: '張宇辰', work_title: '調整與修改Unity中的物件', work_content: '負責處理遊戲引擎Unity中的物件與場景的互動模式，包括移動、拿取放下、與選單互動等' },
        { filename: '30927', name: '李佳翰', work_title: '製作網站及調整與修改Unity中的物件', work_content: '負責製作網站與更新、維護，並幫忙處理遊戲引擎Unity的相關工作' },
        { filename: '31396', name: '施品伃', work_title: '美術場景製作與文書相關事宜', work_content: '負責製作美術場景與物件模型，並處理報告、競賽等文書作業' },
        { filename: '31453', name: '甯子倢', work_title: '美術場景製作與AI客服', work_content: '負責製作美術場景與物件模型，並製作、訓練AI客服機器人的模型' },
    ]
    return (
        <>
            <Head>
                <title>MVR-團隊成員</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <meta httpEquiv="Content-Language" content="en" />
            </Head>

            <main style={{ height: 'calc(100vh - 90px)', overflow: 'hidden', backgroundColor: 'white' }}>
                <div className='m-4 p-2 rounded' style={{ color: 'black' }}>
                    <div style={{ marginTop: "5rem" }}>
                        <h1 className='fw-bold text-dark text-center mt-2' style={{ marginBottom: '4rem' }}>團隊成員</h1>

                        <Slider {...settings}>
                            {teamData.map((data, i) => (
                                <div key={i} className='d-flex gap-3 mx-4' style={{ marginTop: '2rem', marginBottom: '2rem', fontSize: '1.2em' }}>
                                    <Member data={data} />
                                </div>
                            ))}
                        </Slider>

                    </div>
                </div>
            </main>
            <style jsx global>{`
            .slick-prev, .slick-next {
                font-size: 30px; 
                z-index: 1;
            }

            

                .slick-prev:before, .slick-next:before {
                    color: rgba(0, 0, 0, 0.7); 
                }
                .work-content-container {
                    max-height: 150px;
                    overflow-y: auto;
                }

                
            `}</style>
        </>
    )
}
