import Head from 'next/head'
import Image from 'next/legacy/image';
import Stack from 'react-bootstrap/Stack';

type MemberContent = {
    name:string;
    filename:string;
    work_title:string;
    work_content:string;
}

function Member({data}:{data:MemberContent})
{
    return (
        <>
            <div className='w-25'>
                <Image src={`/avatar/${data.filename}.webp`} alt={data.filename} width="600" height="600" className='rounded'/>
            </div>
            <div className='my-1 text-white w-75'>
                <h2 className='text-primary fw-bolder'>{data.name}</h2>
                <h4>{data.work_title}</h4>
                <h4 className='lh-base'>工作內容：{data.work_content}</h4>
            </div>
        </>
    )
}

export default function IntroduceTeam()
{
    const teamData:MemberContent[] = [
        {filename:'30448', name:'孫耀庭', work_title:'規劃流程與管理', work_content:'負責制定開發目標、短期長期目標與明確的日程規劃，後續進行追蹤與微調'},
        {filename:'30414', name:'劉宣珉', work_title:'挑選物件模型、背景與製作', work_content:'負責尋找可使用的物件資源，進行修改與調整，製作成需要的樣貌'},
        {filename:'30141', name:'張宇辰', work_title:'調整與修改Unity中的物件', work_content:'負責處理遊戲引擎Unity中的物件與場景的互動模式，包括移動、拿取放下、與選單互動等'},
        {filename:'30927', name:'李佳翰', work_title:'製作網站及調整與修改Unity中的物件', work_content:'負責製作網站與更新、維護，並幫忙處理遊戲引擎Unity的相關工作'},
        {filename:'31396', name:'施品伃', work_title:'美術場景製作與文書相關事宜', work_content:'負責製作美術場景與物件模型，並處理報告、競賽等文書作業'},
        {filename:'31453', name:'甯子倢', work_title:'美術場景製作與AI客服', work_content:'負責製作美術場景與物件模型，並製作、訓練AI客服機器人的模型'},
    ]
    return (
        <>
        <Head>
        <title>MVR-團隊成員</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
            <div className='m-4 p-2 bg-secondary bg-gradient rounded'>
                <Stack gap={4}>
                    <h1 className='fw-bold text-white text-center mt-2'>團隊成員</h1>
                    {teamData.map((_, i) => (
                        <div key={i} className='d-flex gap-3 mx-4'>
                            <Member data={teamData[i]}/>
                        </div>
                    ))}                    
                </Stack>
            </div>
        </main>
        </>
    )
}