import Head from 'next/head'
import Image from 'next/legacy/image';
import Stack from 'react-bootstrap/Stack';
import Slider from 'react-slick';
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

type MemberContent = {
    name: string;
    filename: string;
    work_title: string;
    work_content: string;
}

function Member({ data }: { data: MemberContent }) {
    return (
        <>
            <div className='w-25' style={{ marginLeft: '5rem' }}>
                <Image src={`/avatar/${data.filename}.webp`} alt={data.filename} width="600" height="600" className='rounded' />
            </div>
            <div className='d-flex align-items-center justify-content-center text-dark w-75'>
                <div>
                    <h2 className='fw-bolder' style={{ fontSize: '4em', color: '#4d86b3' }}>{data.name}</h2>
                    <h4 style={{ fontSize: '1.75em' }}>{data.work_title}</h4>
                    <div className='lh-base work-content-container' style={{ fontSize: '1.5em', maxWidth: '600px', wordWrap: 'break-word' }}>工作內容：{data.work_content}</div>
                </div>
            </div>
            <style jsx>{`
                .work-content-container {
                    height: 130px;  
                    overflow: hidden;
                }
            `}</style>
        </>
    );
}




export default function IntroduceTeam() {
    const settings = {
        dots: true,
        infinite: true,
        speed: 500,
        slidesToShow: 1,
        slidesToScroll: 1,
        dotsClass: "slick-dots slick-thumb",
    };

    const teamData: MemberContent[] = [
        { filename: '30448', name: '孫耀庭', work_title: '專案負責人', work_content: '負責制定開發目標、時程流程規劃、進行後續追蹤與調整專案內容、負責多人遊戲部分開發、協助團隊成員各項事項，包括協作美術組、技術組、文書組。' },
        { filename: '30414', name: '劉宣珉', work_title: '美術組成員 & 文書組成員', work_content: '負責美術相關場景創作、根據需求修改與調整、尋找相對應的美術素材、協作 文書檔案，處理關於美術類型與文書資料調整。' },
        { filename: '30141', name: '張宇辰', work_title: '技術組成員', work_content: '負責處理遊戲引擎Unity中物件與場景的交互動作，包括影音開發、物件創造、選單互動、樂器處理等，處理有關Unity的相關技術。' },
        { filename: '30927', name: '李佳翰', work_title: '技術組成員', work_content: '負責網站前端架設與開發、協作虛擬引擎 Unity 中的相關事項，包括角色修改、Unity與網站的連線等，有關網站與Unity相關技術。' },
        { filename: '31396', name: '施品伃', work_title: '美術組成員 & 文書組成員', work_content: '負責美術相關場景製作、負責文書相關工作，包含:整理、彙整、影片製作、 簡報等，處理美術場景創作以及相關文書資料。' },
        { filename: '31453', name: '甯子倢', work_title: '技術組成員', work_content: '負責網站前後端以及資料庫的架設、開發、維護，AI客服機器人模型的訓練導入，處理關於AI角色以及網站相關技術' },
    ]
    return (
        <>
            <Head>
                <title>MVR-團隊成員</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <meta httpEquiv="Content-Language" content="zh-TW" />
            </Head>

            <main style={{ height: 'calc(100vh - 90px)', overflow: 'hidden', backgroundColor: 'white' }}>
                <div className='m-4 p-2 rounded' style={{ color: 'black' }}>
                    <div style={{ marginTop: "5rem" }}>
                        <h1 className='fw-bold text-dark text-center mt-2' style={{ marginBottom: '4rem' }}>團隊成員</h1>

                        <Slider {...settings}>
                            {teamData.map((data, i) => (
                                <div key={i} className='d-flex gap-3 mx-4' style={{ marginTop: '2rem', marginBottom: '2rem', fontSize: '1.2em' }}>
                                    <Member data={data} />
                                </div>
                            ))}
                        </Slider>

                    </div>
                </div>
            </main>
            <style jsx global>{`
                .slick-prev, .slick-next {
                    font-size: 30px; 
                    z-index: 1;
                }

                .slick-prev:before, .slick-next:before {
                    color: rgba(0, 0, 0, 0.7); 
                }

                .work-content-container {
                    font-size: 10em;
                    max-height: 200px;
                    overflow-y: auto;
                }

                
            `}</style>
        </>
    )
}
